### ISSUE TITLE
[AVM Module Issue]: databricks-workspace access connector output resource id value.

### ISSUE THREAD

**Issue by Dipak-Mistry-WTW** [Azure/terraform-azurerm-avm-res-databricks-workspace#31]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

Just need more output values.  Specifically for me the azurerm_databricks_access_connector resource id value.

**Comment by segraef** [comment]
fixed via #29
